### ISSUE TITLE
Order detail improvements

### ISSUE THREAD

**Issue by jslemmer** [jslemmer/cafe#15]
- Adjust text in button in menu
- Alter current order list, to look visually like this (similar)
- Only orders of today, if there are no orders yet, show a message "no orders for today yet"
- The orders are sorted by their time
- The "pay" button allows to the order to be marked, as "payed". Add a green line around the order.
- The "edit" button loads, the "create order screen" with the current items selected and allows for editing them.  

![current-orders](https://cloud.githubusercontent.com/assets/16065891/12019101/d0968f5a-ada6-11e5-93d4-e6bf25ed693f.jpg)

**Comment by jslemmer** [comment]
You may need to test how many orders can be listed next to each other and how high they should be.
Most orders are 2 to 4 items. Not a lot of items. So maybe 5-6 lines maximum.

**Comment by MarshallCN** [comment]
The latest orders info interface
![1](https://cloud.githubusercontent.com/assets/16070638/12370511/dad0c4fc-bc4e-11e5-9f88-c1cb59ea0090.png)

**Comment by jslemmer** [comment]
It's looking good, but there are issues with clicking the "pay" button.
It tries to open an external page (sql.php?sql=...)

But it crashes and this is quite unsafe as the SQL is in the URL, this could be changed into any SQL.
Which could potentially cause issues in the database if someone abuses it.

**Comment by jslemmer** [comment]
Looks great, good job
