### ISSUE TITLE
Order page

### ISSUE THREAD

**Issue by jslemmer** [jslemmer/cafe#2]
Here are some suggested changes:

- Dropdown list with customer name
- Quick overview of selected products on right side + submit button
- Bookmark links on top of page to quickly goto the right category
- Smaller area for selecting products and big + and - buttons for easier selection

![order-page](https://cloud.githubusercontent.com/assets/16065891/11457764/55fc4e86-96ec-11e5-9a27-7c997266f9da.jpg)

**Comment by MarshallCN** [comment]
How to make these big + and - buttons ?
![image](https://cloud.githubusercontent.com/assets/16070638/11927302/9036c240-a806-11e5-8867-e6da9b35cbb3.png)
I can  this.
![image](https://cloud.githubusercontent.com/assets/16070638/11927355/f46b562c-a806-11e5-8362-a042b875e3b9.png)

**Comment by jslemmer** [comment]
What you have now is already great.
But this is the example I used in the picture.

http://bootsnipp.com/snippets/featured/buttons-minus-and-plus-in-input
(You need a VPN to load this)

**Comment by jslemmer** [comment]
Great progress. Here are some additional suggestions, to make it more usable.

- Add a "create order" button at the top (same button as the at the bottom)
- Make the order overview (what you are about to order) sticky just like the links with the categories on the left
- If you create an order, the form is empty (no customer selected, no food selected) If you want to add something after you clicked "create order" you need to select everything again.

**Comment by MarshallCN** [comment]
- In latest version, you can click "modify" to edit order.
![image](https://cloud.githubusercontent.com/assets/16070638/11977438/e1b6267a-a9bd-11e5-9e5d-46dfec51ab73.png)
![image](https://cloud.githubusercontent.com/assets/16070638/11977443/ed353b9e-a9bd-11e5-9902-3040ca4a6d0f.png)
- the order overview may out of screen if it's too long.
the order overview is sticky now, so I can't scroll down
![Uploading QQ截图20151223215812.jpg…]()

**Comment by MarshallCN** [comment]
- the order overview may out of screen if it's too long. the order overview is sticky now, so I can't scroll down 
![qq 20151223215812](https://cloud.githubusercontent.com/assets/16070638/11977927/1e43dc50-a9c2-11e5-9db0-7b94b2ad7a50.jpg)

**Comment by MarshallCN** [comment]
* the big +/- button of latest version
![image](https://cloud.githubusercontent.com/assets/16070638/11993358/e7b1e412-aa6a-11e5-8ce4-7b833506a171.png)

**Comment by jslemmer** [comment]
This page is almost super awesome.

I would suggest, not doing a dropdown here, but move the reset to the order area and only show it, when there is some information. As now I can click it, when I did not order anything yet.

And just make the button, do the "create order". Just as a single button.
Now to order you have to move your mouse 2 times. Over the button and then to the create.

Which is a bit inconvenient. Thanks!

<img width="1327" alt="create-reset" src="https://cloud.githubusercontent.com/assets/16065891/12008628/97c0707a-ac83-11e5-858e-771e95bfd920.png">

**Comment by jslemmer** [comment]
Hey Marshall,

I re-arranges/styled the buttons a bit. And I have the following suggestions:

- Remove the red parts (ID, phone, address, food type)
- Move the customer name to the top
- Move the date/time to the right

<img width="1369" alt="screen shot 2015-12-28 at 14 09 18" src="https://cloud.githubusercontent.com/assets/16065891/12014798/c5cf0b1c-ad6d-11e5-9fef-6a5e3b9beddc.png">

**Comment by MarshallCN** [comment]
- latest version
![image](https://cloud.githubusercontent.com/assets/16070638/12017129/e076cc64-ad8d-11e5-88cc-e12366f4540b.png)

![image](https://cloud.githubusercontent.com/assets/16070638/12017121/bc5e1ee0-ad8d-11e5-97fe-ffe398d37eaf.png)

**Comment by jslemmer** [comment]
That is a good solution as well, but make the product bold text.
The category is not so important.

**Comment by MarshallCN** [comment]
![image](https://cloud.githubusercontent.com/assets/16070638/12017544/146b5c88-ad93-11e5-8170-db1ee8903236.png)

**Comment by jslemmer** [comment]
Perfect !
