### ISSUE TITLE
Create a new Weekly sales overview

### ISSUE THREAD

**Issue by jslemmer** [jslemmer/cafe#22]
The weekly report should be of this nature, with the option to select the current week, last week, last month and a start/end date to generate the report. See attached example

[report.pdf](https://github.com/jslemmer/cafe/files/150415/report.pdf)

**Comment by MarshallCN** [comment]
![1](https://cloud.githubusercontent.com/assets/16070638/13548201/a1066e36-e325-11e5-807b-41410753a5be.png)
![2](https://cloud.githubusercontent.com/assets/16070638/13548202/a64c16d4-e325-11e5-8920-c79a88e8190c.png)

**Comment by jslemmer** [comment]
Very nice, can you add a print button at the top as well

<img width="1340" alt="screen shot 2016-03-07 at 14 05 22" src="https://cloud.githubusercontent.com/assets/16065891/13561953/cf85a382-e46d-11e5-82c0-3d4861728964.png">

**Comment by MarshallCN** [comment]
Latest commit has two print button

**Comment by jslemmer** [comment]
Very nice, fixed :+1:
