### ISSUE TITLE
Make last name not required, only first name is required

### ISSUE THREAD

**Issue by jslemmer** [jslemmer/cafe#25]
<img width="1240" alt="screen shot 2016-03-07 at 14 12 54" src="https://cloud.githubusercontent.com/assets/16065891/13562053/c11127ee-e46e-11e5-8b7a-2b718fce22cd.png">

**Comment by jslemmer** [comment]
commit seems to address the issue

**Comment by jslemmer** [comment]
I updated the code in the cafe. But the customers do not save if I leave the last name empty.

**Comment by MarshallCN** [comment]
The problem should be fixed now in latest commit

**Comment by jslemmer** [comment]
Fixed :)
