### ISSUE TITLE
Weekly report - add daily profit

### ISSUE THREAD

**Issue by jslemmer** [jslemmer/cafe#30]
Can we also add the daily profit to the weekly report.
See attached example, like in the excel.

Helps the management, see how much is sold each day.

Now only the weekly total is available

![820736554](https://cloud.githubusercontent.com/assets/16065891/13771138/af0624a6-eac6-11e5-8c10-ab0345116645.jpg)

**Comment by jslemmer** [comment]
if needed, you can remove the print button at the bottom of this overview

**Comment by MarshallCN** [comment]
![123](https://cloud.githubusercontent.com/assets/16070638/13818825/64c0e9b4-ebd2-11e5-912b-195993511162.JPG)

**Comment by jslemmer** [comment]
Awesome fixed!
