### ISSUE TITLE
Menu & categories management

### ISSUE THREAD

**Issue by jslemmer** [jslemmer/cafe#32]
There is no easy way of managing these now, except directly in the database

**Comment by MarshallCN** [comment]
add "New Food" page and food manage function
![321](https://cloud.githubusercontent.com/assets/16070638/13898600/4f252e26-ee11-11e5-8779-1ae8effc551c.jpg)
![123](https://cloud.githubusercontent.com/assets/16070638/13898573/9802db62-ee10-11e5-8fb1-5d6c07afb3a3.jpg)

**Comment by jslemmer** [comment]
Seems to have the basic functionality
