### ISSUE TITLE
Add time condition - Yesterday

### ISSUE THREAD

**Issue by jslemmer** [jslemmer/cafe#33]
A time condition for selecting orders of yesterday would be convenient

<img width="242" alt="screen shot 2016-03-15 at 19 25 24" src="https://cloud.githubusercontent.com/assets/16065891/13776185/c807780c-eae3-11e5-9d29-5c6ce8a83beb.png">

**Comment by MarshallCN** [comment]
Add "yesterday" in latest commit
![312](https://cloud.githubusercontent.com/assets/16070638/13845524/86919472-ec7b-11e5-9b8a-c319395a22c6.jpg)

**Comment by jslemmer** [comment]
yup :)
