### ISSUE TITLE
Separate Print, Pay, Edit, Delete buttons (Color coded) 

### ISSUE THREAD

**Issue by jslemmer** [jslemmer/cafe#34]
No need to implement this until the POS printer function is implemented and working well (#35) 

Color codes
- Green: #0ab159 (Or use this as an alternative if it is too bright: #94e39d)
- Red: #d8596b

<img width="475" alt="screen shot 2016-03-15 at 19 25 09" src="https://cloud.githubusercontent.com/assets/16065891/13777384/ceae340a-eaea-11e5-9e86-2bd4dd0116f0.png">

**Comment by MarshallCN** [comment]
![321](https://cloud.githubusercontent.com/assets/16070638/13845402/b7fd0420-ec7a-11e5-97a8-a1fb212b5f47.jpg)
Change buttons color

**Comment by jslemmer** [comment]
awesome :+1:
