### ISSUE TITLE
Implement POS printing functionality

### ISSUE THREAD

**Issue by jslemmer** [jslemmer/cafe#35]
Based on a POS printer like this: https://item.taobao.com/item.htm?spm=a1z0k.7630242.1997989073.d4919141.aqXdLo&id=24439128103&_u=f22rfe2uf464

Have a button that once pressed allows printing in a correct format to the POS printer, so it can be used in the kitchen.

**Comment by jslemmer** [comment]
Can you double check with the seller on taobao that this printer can accept: esc/pos

And this php framework should support this printer: https://github.com/mike42/escpos-php

**Comment by MarshallCN** [comment]
The didn't reply me yet, if they tell me I'll let u know. And I also find anther one could use esc/pos,
https://detail.tmall.com/item.htm?spm=a230r.1.14.1.5p489M&id=43415114300&ns=1&abbucket=17&sku_properties=5919063:6536025
![123](https://cloud.githubusercontent.com/assets/16070638/13883216/75a9045e-ed63-11e5-9a23-8cb5773acead.jpg)
The php framework github site have a list of printer that can work with, it includes the 'Xprinter...' which have same label as this one
![45](https://cloud.githubusercontent.com/assets/16070638/13883235/99840e28-ed63-11e5-8b2d-8a727d5cbfff.jpg)

**Comment by jslemmer** [comment]
Having quite some issues on instaling the printer, but this command now seems to work:

lpr -o raw -H localhost -P POS58 bla.txt

**Comment by jslemmer** [comment]
Used this source install and configure CUPS

**Comment by jslemmer** [comment]
For reference this POS was puchased on Taobao

https://item.taobao.com/item.htm?spm=a1z09.2.0.0.tKF41p&id=44188580582&_u=s22rfe2ufee1

<img width="943" alt="screen shot 2016-03-28 at 17 02 25" src="https://cloud.githubusercontent.com/assets/16065891/14074886/fc3de11a-f506-11e5-98dc-c6ffb710aaae.png">

**Comment by MarshallCN** [comment]
I saw there're "NULL" in the sample receipt.txt, is that necessary? What if you delete the 'NULL', can it still work?
![null](https://cloud.githubusercontent.com/assets/16070638/14108556/910689e8-f5f0-11e5-892b-c25bb4f8f067.jpg)
I found 2 methods which may solve print problem, but one of these method can not print "NULL"

**Comment by MarshallCN** [comment]
Method 1:
First echo the dynamic php code, and make it as a file,
Then use shell_exec(...) to make a receipt.txt file, and printer can print it.
![m1](https://cloud.githubusercontent.com/assets/16070638/14108682/0f626ffa-f5f1-11e5-8800-ef482060fb28.jpg)
![m1a](https://cloud.githubusercontent.com/assets/16070638/14108684/12a21508-f5f1-11e5-81ff-0190f0c4eb13.jpg)

**Comment by MarshallCN** [comment]
Method 2:
Just replace the worlds in the receipt.txt to create dynamic files,
but the "null"
![m2](https://cloud.githubusercontent.com/assets/16070638/14108939/275cae6c-f5f2-11e5-87d7-d3c3193b52fa.jpg)

**Comment by jslemmer** [comment]
I'm not sure what the NUL does, but seems important.
I think the first approach is very creative :) Which could be a solution.

----------

However it seems it should be possible to pass a variable to the shell_exec method.
See example: http://stackoverflow.com/questions/16932113/passing-variables-to-shell-exec

$page = shell_exec('/tmp/my_script.php "{$my_url}" "{$my_refer}"');

But I have not tried it yet. And can't find good documentation on how to use it.

**Comment by jslemmer** [comment]
Or we could use your suggested method (#1), but not write all the code each time.

1. But create a file (id.txt) where we write the ID of the order in.
2. Open id.txt in receipt.php, so we get the ID, run all the queries and then save that as receipt.txt

So you do not have to write all the code into that file each time. Seems a bit to much.
This maybe makes it easier.

What do you think?

**Comment by MarshallCN** [comment]
That's great! Easier way is better! Have you tried the "shell_exec"? Can it pass id into url?

**Comment by jslemmer** [comment]
I have not yet tried and today and tomorrow busy.
You can come try in the cafe if you like.

I can give you the login/password of the Raspberry pi machine.

**Comment by jslemmer** [comment]
See #44 

Implementation works, now just need correct cables to position the printer
