### ISSUE TITLE
Custom time on order

### ISSUE THREAD

**Issue by jslemmer** [jslemmer/cafe#36]
Add button on order create, that shows a input field, where a custom time can be entered.
Some customers order in advance for a specific time. Would be great to record that so that can be printed on the POS receipts.

<img width="1279" alt="screen shot 2016-03-15 at 20 23 13" src="https://cloud.githubusercontent.com/assets/16065891/13777585/043184a0-eaec-11e5-9c6b-b8ba6145d74b.png">

**Comment by MarshallCN** [comment]
Only allow user customing time, but the Date?

**Comment by MarshallCN** [comment]
latest commit

 
when click on time
![123](https://cloud.githubusercontent.com/assets/16070638/13898903/6b429e72-ee1b-11e5-8e6f-89c4b0d3c9a7.jpg)

**Comment by jslemmer** [comment]
Works well enough
