### ISSUE TITLE
Weekly sales not calculated correctly for "Veggie power"

### ISSUE THREAD

**Issue by jslemmer** [jslemmer/cafe#39]
See screenshot, it's showing: NaN

<img width="1209" alt="screen shot 2016-03-21 at 14 47 55" src="https://cloud.githubusercontent.com/assets/16065891/13913123/ae14768a-ef7e-11e5-9458-00ea2452138a.png">

**Comment by MarshallCN** [comment]
![123](https://cloud.githubusercontent.com/assets/16070638/13916310/ce879ae4-ef94-11e5-8284-035db686a71c.JPG)

I didn't find this problem on my computer, can you send your database.sql to me?

**Comment by MarshallCN** [comment]
There're some differences between our DB, and I edit my code base on your DB, this problem should be solved now
![123](https://cloud.githubusercontent.com/assets/16070638/13984408/089c97aa-f131-11e5-93d2-83940f6d92bc.png)

**Comment by MarshallCN** [comment]
Although this problem won't happen any more, I still suggest that set food type's catalog_id = its food_id if you will use phpadmin to add new food type. This's also what I do in the "add food cata" page, the catalog_id will be automatically set equal to food_id for new food cata 
![123](https://cloud.githubusercontent.com/assets/16070638/13984686/c9a9c5b6-f132-11e5-9d9d-a1ff1d5326e3.JPG)

**Comment by jslemmer** [comment]
Looks fixed indeed :+1:
