### ISSUE TITLE
Adjust menu & make it sticky at the top

### ISSUE THREAD

**Issue by jslemmer** [jslemmer/cafe#5]
Some suggestions for adjusting the menu.

- make it sticky, so that it is always at the top (pages flow below it)
- Look at screenshot. The primary action is creating an order and secondary is looking at the orders. The rest can be hidden in a menu. Here is an example of how you can make such a menu: http://www.w3schools.com/bootstrap/bootstrap_dropdowns.asp

See screenshot as well

![menu](https://cloud.githubusercontent.com/assets/16065891/11945919/e47c809a-a88f-11e5-9691-f73298727c5f.jpg)

**Comment by MarshallCN** [comment]
- latest version
![image](https://cloud.githubusercontent.com/assets/16070638/11978601/d1f9fd7e-a9c7-11e5-8400-5b1a4cc7e470.png)
![image](https://cloud.githubusercontent.com/assets/16070638/11978615/e504e71c-a9c7-11e5-9c28-8b16ed20f3a7.png)

**Comment by MarshallCN** [comment]
- Merry Christmas!

![2](https://cloud.githubusercontent.com/assets/16070638/12004773/266d5cb2-abb1-11e5-9c09-f6276ef37273.jpg)
![3](https://cloud.githubusercontent.com/assets/16070638/12004774/275a5378-abb1-11e5-8e7c-4c8e1cfbdb12.jpg)

**Comment by jslemmer** [comment]
Haha, nice Christmas to you too :)
The sticky menu is great :+1: 

But can you adjust the menu like I have shown in this picture.
So the order of the buttons and hide other buttons under that dropdown?

![image](https://cloud.githubusercontent.com/assets/16065891/12008621/13eeabea-ac83-11e5-8539-ddf709c2ca21.png)

**Comment by jslemmer** [comment]
The menu has been altered as indicated on the picture.
Closing this issue  :+1:
